"""Create Message model

Revision ID: 918adc567b51
Revises: 20ac90237977
Create Date: 2025-06-15 21:14:55.433161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918adc567b51'
down_revision = '20ac90237977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
